import { SvgIconProps } from '@mui/material'
import {
  ArrowRightAltRounded,
  AccessTimeRounded,
  AddRounded,
  ApartmentRounded,
  ArrowBackIosRounded,
  ArrowBackRounded,
  ArrowDownward,
  ArrowForwardIosRounded,
  ArrowForwardRounded,
  Assessment,
  AttachFile,
  BarChartRounded,
  BlockRounded,
  BrandingWatermarkRounded,
  BusinessRounded,
  Camera,
  CameraAlt,
  Close,
  CloseRounded,
  ContentCopyRounded,
  DeleteForeverRounded,
  DeleteOutline,
  DeleteRounded,
  DirectionsCar,
  DoneRounded,
  DownloadRounded,
  DragHandleRounded,
  EditOffRounded,
  EditRounded,
  ExpandLess,
  ExpandMore,
  FileCopy,
  FileUploadRounded,
  FolderSpecial,
  GetAppRounded,
  Group,
  GroupWork,
  HomeRounded,
  HomeWorkRounded,
  Inbox,
  InsertDriveFile,
  LocalCarWash,
  LocalHospital,
  LocationCityRounded,
  MeetingRoomRounded,
  Mic,
  MicOff,
  MoreVertRounded,
  OpenInNewRounded,
  PersonRounded,
  Phone,
  RotateRight,
  SaveRounded,
  Search,
  SearchRounded,
  Settings,
  SupervisorAccount,
  VideoCall,
  Videocam,
  VideocamOff,
  VisibilityOffRounded,
  VisibilityRounded,
  CalendarToday,
  Payment,
  Build,
  MenuOpen,
  HelpRounded,
  ArrowDropUpRounded,
  ArrowDropDownRounded,
  MenuRounded,
  ManageSearchRounded,
  Brightness1,
  ViewColumnRounded,
  ListRounded,
  TuneRounded,
  CompareArrowsRounded,
  CheckRounded,
  MailOutlineRounded,
  WhatsApp,
  PhoneRounded,
  StickyNote2Rounded,
  TaskRounded,
  InsertDriveFileRounded,
  CancelRounded,
  NearMeRounded,
  FormatColorTextRounded,
  AttachFileRounded,
  InsertLinkRounded,
  SentimentSatisfiedAltRounded,
  AddPhotoAlternateRounded,
  DriveFileRenameOutlineRounded,
  VerticalSplitRounded,
  FormatBoldRounded,
  FormatItalicRounded,
  EmailRounded,
  NoteAltRounded,
  TaskAltRounded,
  SwapHorizRounded,
  WorkRounded,
  PhoneForwardedRounded,
  ComputerRounded,
  MicOffRounded,
  PersonOutlineRounded,
  HouseRounded,
  PhoneAndroidRounded,
  PhoneInTalkRounded,
  FormatListNumberedRounded,
  FormatListBulletedRounded,
  CallEndRounded,
  SaveAsRounded,
  MicNoneRounded,
  PlayArrowRounded,
  DoneAllRounded,
  FormatSizeRounded,
  FormatAlignLeftRounded,
  OpenInFullRounded,
  CloseFullscreenRounded,
  MoreHorizRounded,
  PhotoLibraryRounded,
  RuleRounded,
  AlarmRounded,
  FormatUnderlinedRounded,
  FormatAlignRightRounded,
  FormatAlignCenterRounded,
  TitleRounded,
  SubdirectoryArrowLeftRounded,
  UnfoldMoreRounded,
  TimerRounded,
  CategoryRounded,
  DynamicFormRounded,
  ErrorOutlineRounded,
  CheckBoxRounded,
  CheckBoxOutlineBlankRounded,
  PauseRounded,
  StopRounded,
  ViewWeekRounded,
  WarningAmberOutlined,
  PhoneDisabledRounded,
  MarkChatUnread,
  UnfoldLessRounded,
  InsertDriveFileSharp,
  SubjectSharp,
  SpeakerNotesOff,
  CheckCircleOutlineRounded,
  ReplyRounded,
  ControlPointDuplicate,
  StarBorder,
  StarRate,
  RadioButtonChecked,
  RadioButtonUnchecked,
  PowerRounded,
  PriorityHighRounded,
  AccountCircleRounded,
  Notifications,
} from '@mui/icons-material'
export const icons = {
  add: AddRounded,
  apartment: ApartmentRounded,
  arrowBack: ArrowBackIosRounded,
  arrowBackRounded: ArrowBackRounded,
  arrowDownward: ArrowDownward,
  arrowForward: ArrowForwardIosRounded,
  arrowForwardRounded: ArrowForwardRounded,
  assessment: Assessment,
  attachFile: AttachFile,
  barChart: BarChartRounded,
  brandingWatermark: BrandingWatermarkRounded,
  business: BusinessRounded,
  calendarToday: CalendarToday,
  camera: Camera,
  cameraAlt: CameraAlt,
  close: Close,
  closeRounded: CloseRounded,
  contentCopyRounded: ContentCopyRounded,
  delete: DeleteOutline,
  deleteFill: DeleteRounded,
  deleteRounded: DeleteForeverRounded,
  directionsCar: DirectionsCar,
  doneRounded: DoneRounded,
  dragHandle: DragHandleRounded,
  editOffRounded: EditOffRounded,
  editRounded: EditRounded,
  expandLess: ExpandLess,
  expandMore: ExpandMore,
  file: FileCopy,
  fileUploadRounded: FileUploadRounded,
  folderSpecial: FolderSpecial,
  getApp: GetAppRounded,
  group: Group,
  groupWork: GroupWork,
  home: HomeRounded,
  homeWork: HomeWorkRounded,
  inbox: Inbox,
  insertDriveFile: InsertDriveFile,
  insertDriveFileSharp: InsertDriveFileSharp,
  localCarWash: LocalCarWash,
  localHospital: LocalHospital,
  locationCity: LocationCityRounded,
  meetingRoom: MeetingRoomRounded,
  mic: Mic,
  micOff: MicOff,
  moreVertRounded: MoreVertRounded,
  openInNewRounded: OpenInNewRounded,
  person: PersonRounded,
  phone: Phone,
  save: SaveRounded,
  search: Search,
  searchRounded: SearchRounded,
  settings: Settings,
  spinner: RotateRight,
  supervisorAccount: SupervisorAccount,
  videoCall: VideoCall,
  videocam: Videocam,
  videocamOff: VideocamOff,
  visibilityOffRounded: VisibilityOffRounded,
  visibilityRounded: VisibilityRounded,
  requestQuote: Payment,
  build: Build,
  menuOpen: MenuOpen,
  help: HelpRounded,
  arrowDropUp: ArrowDropUpRounded,
  arrowDropDown: ArrowDropDownRounded,
  menu: MenuRounded,
  moreDetails: ManageSearchRounded,
  notificationRounded: Brightness1,
  viewColumnRounded: ViewColumnRounded,
  listRounded: ListRounded,
  check: CheckRounded,
  tuneRounded: TuneRounded,
  compareArrowsRounded: CompareArrowsRounded,
  starBorder: StarBorder,
  starRate: StarRate,
  radioButtonUnchecked: RadioButtonUnchecked,
  radioButtonChecked: RadioButtonChecked,
  mailOutlined: MailOutlineRounded,
  whatsapp: WhatsApp,
  phoneRounded: PhoneRounded,
  phoneDisabledRounded: PhoneDisabledRounded,
  stickyNote: StickyNote2Rounded,
  taskRounded: TaskRounded,
  fileRounded: InsertDriveFileRounded,
  closeCircle: CancelRounded,
  sendArrow: NearMeRounded,
  textOptions: FormatColorTextRounded,
  attachRounded: AttachFileRounded,
  insertLink: InsertLinkRounded,
  emoji: SentimentSatisfiedAltRounded,
  addPhoto: AddPhotoAlternateRounded,
  signature: DriveFileRenameOutlineRounded,
  template: VerticalSplitRounded,
  boldFormat: FormatBoldRounded,
  italicFormat: FormatItalicRounded,
  underlineFormat: FormatUnderlinedRounded,
  emailRounded: EmailRounded,
  noteAlt: NoteAltRounded,
  taskAlt: TaskAltRounded,
  swapHoriz: SwapHorizRounded,
  briefcaseRounded: WorkRounded,
  phoneForwarded: PhoneForwardedRounded,
  computerRounded: ComputerRounded,
  micOffRounded: MicOffRounded,
  personOutlined: PersonOutlineRounded,
  houseRounded: HouseRounded,
  phoneAndroid: PhoneAndroidRounded,
  phoneInTalk: PhoneInTalkRounded,
  formatListNumber: FormatListNumberedRounded,
  formatListBullet: FormatListBulletedRounded,
  callEnd: CallEndRounded,
  saveAs: SaveAsRounded,
  micNone: MicNoneRounded,
  playArrow: PlayArrowRounded,
  doubleCheck: DoneAllRounded,
  fontSize: FormatSizeRounded,
  formatAlignLeft: FormatAlignLeftRounded,
  formatAlignCenter: FormatAlignCenterRounded,
  formatAlignRight: FormatAlignRightRounded,
  openFullScreen: OpenInFullRounded,
  closeFullScreen: CloseFullscreenRounded,
  downloadRounded: DownloadRounded,
  moreHoriz: MoreHorizRounded,
  photoLibrary: PhotoLibraryRounded,
  rule: RuleRounded,
  alarm: AlarmRounded,
  titleRounded: TitleRounded,
  enterArrow: SubdirectoryArrowLeftRounded,
  unfoldLess: UnfoldLessRounded,
  unfoldMore: UnfoldMoreRounded,
  viewWeek: ViewWeekRounded,
  timer: TimerRounded,
  category: CategoryRounded,
  dynamicForm: DynamicFormRounded,
  error: ErrorOutlineRounded,
  pending: AccessTimeRounded,
  checkboxChecked: CheckBoxRounded,
  checkboxBlank: CheckBoxOutlineBlankRounded,
  pause: PauseRounded,
  stop: StopRounded,
  viewWeekRounded: ViewWeekRounded,
  warningAmberOutlined: WarningAmberOutlined,
  markChatUnread: MarkChatUnread,
  block: BlockRounded,
  textSharp: SubjectSharp,
  speakerNotesOff: SpeakerNotesOff,
  checkCircleOutlineRounded: CheckCircleOutlineRounded,
  arrowRightAltRounded: ArrowRightAltRounded,
  reply: ReplyRounded,
  controlPointDuplicate: ControlPointDuplicate,
  powerRounded: PowerRounded,
  priorityHighRounded: PriorityHighRounded,
  accountCircle: AccountCircleRounded,
  notifications: Notifications,
}

export interface IconProps extends SvgIconProps {
  icon: keyof typeof icons
}
const Icon = ({
  icon,
  color = `inherit`,
  ...props
}: IconProps): JSX.Element => {
  const IconComponent = icons[icon]
  return <IconComponent color={color} {...props} />
}
export default Icon
